package firstaid

import (
	"math/rand"
)

var catchphrases = []string{
	"Because, inevitably, something will go wrong.",
	"Here to help, unless you typed 'exit'.",
	"We make command line errors less catastrophic... usually.",
	"For when your command line gives you sass instead of success.",
	"Think of us as your last resort. No, really.",
	"Saving your command line from itself since 2024.",
	"Don’t panic. But if you do, type 'first-aid'.",
	"Helping you fix what shouldn’t have been broken in the first place.",
	"Errors are inevitable. Despair is optional.",
	"Let’s decode what you did this time.",
	"Remember, it’s only a disaster if you can’t fix it.",
	"Oh, a typo? What a surprise!",
	"Command wrong? Let’s pretend it never happened.",
	"Yes, even this can be fixed. Probably.",
	"Turning ‘oops’ into ‘aha’ moments, sometimes.",
	"Stuck? Just another day in the console.",
	"Helping you find new and innovative ways to break things.",
	"When your prompt needs more than just a nudge.",
	"Ask anything—except for the meaning of life.",
	"The smart way to pretend you know what you’re doing.",
	"Unleash the power of AI on your command line (caution advised).",
	"Elevate your command line, diminish your troubles.",
	"The ultimate companion for when you mistype, but won’t admit it.",
	"For those who know enough to know they need help.",
	"Turning your typos into triumphs.",
	"Because even command lines have feelings.",
	"Keep calm and code on, with a little help from AI.",
	"Debug with dignity (and a bit of AI).",
	"Solving code crises, the classy way.",
	"When coding gets tough, the tough get AI.",
	"Hit a snag? It’s nothing a little AI can’t handle.",
	"Don’t fret, just type.",
	"Stumped? Let’s unpuzzle it together.",
	"Where there’s a prompt, there’s a way.",
	"Leave the guesswork to us.",
	"Making command line mastery an everyday thing.",
	"Unlock the secrets of your shell.",
	"Command line woes? Consider them solved.",
	"Got command line issues? It’s not terminal... yet.",
	"Feel free to ask. It’s not like AI judges... much.",
	"Why do it yourself when AI can do it (almost) better?",
	"Turning your late nights into slightly less late nights.",
	"Automate the predictable so you can handle the incredible.",
	"Congratulations, you’ve found a new way to break things.",
	"Every command line warrior needs a trusty aide.",
	"Be the hero your command line deserves.",
	"An AI that understands your ‘oops’ moments.",
	"Trouble in terminal town? Call in the cavalry.",
	"Less time guessing, more time pressing.",
	"Don’t let your commands command you.",
	"Break the code, not your spirit.",
	"Your command line’s new best friend.",
	"Making “I don’t know what I’m doing” sound cooler.",
	"Your digital detective, at your service.",
	"Command line calamities? No worries, we’ve seen worse.",
	"Debugging by day, saving sanity by night.",
	"Trust us, your shell has seen scarier things.",
	"When you’re ready to go from “what the shell?” to “oh well”.",
	"Console yourself with some AI assistance.",
	"Life’s too short for manual debugging.",
	"There’s a prompt for that.",
}

func RandomCatchphrase() string {
	return catchphrases[rand.Intn(len(catchphrases))]
}
